package com.media.form.log;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LogOperationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public LogOperationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkOperationIdIsNull() {
            addCriterion("pk_operation_id is null");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdIsNotNull() {
            addCriterion("pk_operation_id is not null");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdEqualTo(String value) {
            addCriterion("pk_operation_id =", value, "pkOperationId");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdNotEqualTo(String value) {
            addCriterion("pk_operation_id <>", value, "pkOperationId");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdGreaterThan(String value) {
            addCriterion("pk_operation_id >", value, "pkOperationId");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdGreaterThanOrEqualTo(String value) {
            addCriterion("pk_operation_id >=", value, "pkOperationId");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdLessThan(String value) {
            addCriterion("pk_operation_id <", value, "pkOperationId");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdLessThanOrEqualTo(String value) {
            addCriterion("pk_operation_id <=", value, "pkOperationId");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdLike(String value) {
            addCriterion("pk_operation_id like", value, "pkOperationId");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdNotLike(String value) {
            addCriterion("pk_operation_id not like", value, "pkOperationId");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdIn(List<String> values) {
            addCriterion("pk_operation_id in", values, "pkOperationId");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdNotIn(List<String> values) {
            addCriterion("pk_operation_id not in", values, "pkOperationId");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdBetween(String value1, String value2) {
            addCriterion("pk_operation_id between", value1, value2, "pkOperationId");
            return (Criteria) this;
        }

        public Criteria andPkOperationIdNotBetween(String value1, String value2) {
            addCriterion("pk_operation_id not between", value1, value2, "pkOperationId");
            return (Criteria) this;
        }

        public Criteria andBeforedataIsNull() {
            addCriterion("beforeData is null");
            return (Criteria) this;
        }

        public Criteria andBeforedataIsNotNull() {
            addCriterion("beforeData is not null");
            return (Criteria) this;
        }

        public Criteria andBeforedataEqualTo(String value) {
            addCriterion("beforeData =", value, "beforedata");
            return (Criteria) this;
        }

        public Criteria andBeforedataNotEqualTo(String value) {
            addCriterion("beforeData <>", value, "beforedata");
            return (Criteria) this;
        }

        public Criteria andBeforedataGreaterThan(String value) {
            addCriterion("beforeData >", value, "beforedata");
            return (Criteria) this;
        }

        public Criteria andBeforedataGreaterThanOrEqualTo(String value) {
            addCriterion("beforeData >=", value, "beforedata");
            return (Criteria) this;
        }

        public Criteria andBeforedataLessThan(String value) {
            addCriterion("beforeData <", value, "beforedata");
            return (Criteria) this;
        }

        public Criteria andBeforedataLessThanOrEqualTo(String value) {
            addCriterion("beforeData <=", value, "beforedata");
            return (Criteria) this;
        }

        public Criteria andBeforedataLike(String value) {
            addCriterion("beforeData like", value, "beforedata");
            return (Criteria) this;
        }

        public Criteria andBeforedataNotLike(String value) {
            addCriterion("beforeData not like", value, "beforedata");
            return (Criteria) this;
        }

        public Criteria andBeforedataIn(List<String> values) {
            addCriterion("beforeData in", values, "beforedata");
            return (Criteria) this;
        }

        public Criteria andBeforedataNotIn(List<String> values) {
            addCriterion("beforeData not in", values, "beforedata");
            return (Criteria) this;
        }

        public Criteria andBeforedataBetween(String value1, String value2) {
            addCriterion("beforeData between", value1, value2, "beforedata");
            return (Criteria) this;
        }

        public Criteria andBeforedataNotBetween(String value1, String value2) {
            addCriterion("beforeData not between", value1, value2, "beforedata");
            return (Criteria) this;
        }

        public Criteria andAfterdataIsNull() {
            addCriterion("afterData is null");
            return (Criteria) this;
        }

        public Criteria andAfterdataIsNotNull() {
            addCriterion("afterData is not null");
            return (Criteria) this;
        }

        public Criteria andAfterdataEqualTo(String value) {
            addCriterion("afterData =", value, "afterdata");
            return (Criteria) this;
        }

        public Criteria andAfterdataNotEqualTo(String value) {
            addCriterion("afterData <>", value, "afterdata");
            return (Criteria) this;
        }

        public Criteria andAfterdataGreaterThan(String value) {
            addCriterion("afterData >", value, "afterdata");
            return (Criteria) this;
        }

        public Criteria andAfterdataGreaterThanOrEqualTo(String value) {
            addCriterion("afterData >=", value, "afterdata");
            return (Criteria) this;
        }

        public Criteria andAfterdataLessThan(String value) {
            addCriterion("afterData <", value, "afterdata");
            return (Criteria) this;
        }

        public Criteria andAfterdataLessThanOrEqualTo(String value) {
            addCriterion("afterData <=", value, "afterdata");
            return (Criteria) this;
        }

        public Criteria andAfterdataLike(String value) {
            addCriterion("afterData like", value, "afterdata");
            return (Criteria) this;
        }

        public Criteria andAfterdataNotLike(String value) {
            addCriterion("afterData not like", value, "afterdata");
            return (Criteria) this;
        }

        public Criteria andAfterdataIn(List<String> values) {
            addCriterion("afterData in", values, "afterdata");
            return (Criteria) this;
        }

        public Criteria andAfterdataNotIn(List<String> values) {
            addCriterion("afterData not in", values, "afterdata");
            return (Criteria) this;
        }

        public Criteria andAfterdataBetween(String value1, String value2) {
            addCriterion("afterData between", value1, value2, "afterdata");
            return (Criteria) this;
        }

        public Criteria andAfterdataNotBetween(String value1, String value2) {
            addCriterion("afterData not between", value1, value2, "afterdata");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andLogNumIsNull() {
            addCriterion("log_num is null");
            return (Criteria) this;
        }

        public Criteria andLogNumIsNotNull() {
            addCriterion("log_num is not null");
            return (Criteria) this;
        }

        public Criteria andLogNumEqualTo(String value) {
            addCriterion("log_num =", value, "logNum");
            return (Criteria) this;
        }

        public Criteria andLogNumNotEqualTo(String value) {
            addCriterion("log_num <>", value, "logNum");
            return (Criteria) this;
        }

        public Criteria andLogNumGreaterThan(String value) {
            addCriterion("log_num >", value, "logNum");
            return (Criteria) this;
        }

        public Criteria andLogNumGreaterThanOrEqualTo(String value) {
            addCriterion("log_num >=", value, "logNum");
            return (Criteria) this;
        }

        public Criteria andLogNumLessThan(String value) {
            addCriterion("log_num <", value, "logNum");
            return (Criteria) this;
        }

        public Criteria andLogNumLessThanOrEqualTo(String value) {
            addCriterion("log_num <=", value, "logNum");
            return (Criteria) this;
        }

        public Criteria andLogNumLike(String value) {
            addCriterion("log_num like", value, "logNum");
            return (Criteria) this;
        }

        public Criteria andLogNumNotLike(String value) {
            addCriterion("log_num not like", value, "logNum");
            return (Criteria) this;
        }

        public Criteria andLogNumIn(List<String> values) {
            addCriterion("log_num in", values, "logNum");
            return (Criteria) this;
        }

        public Criteria andLogNumNotIn(List<String> values) {
            addCriterion("log_num not in", values, "logNum");
            return (Criteria) this;
        }

        public Criteria andLogNumBetween(String value1, String value2) {
            addCriterion("log_num between", value1, value2, "logNum");
            return (Criteria) this;
        }

        public Criteria andLogNumNotBetween(String value1, String value2) {
            addCriterion("log_num not between", value1, value2, "logNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table md_log_operation
     *
     * @mbg.generated do_not_delete_during_merge Sun Nov 25 11:46:30 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table md_log_operation
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}