package com.media.form.log;

import com.media.common.base.BaseModel;
import java.util.Date;

public class LogOperation extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_log_operation.pk_operation_id
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    private String pkOperationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_log_operation.beforeData
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    private String beforedata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_log_operation.afterData
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    private String afterdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_log_operation.create_time
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_log_operation.memo
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_log_operation.log_num
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    private String logNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_log_operation.pk_operation_id
     *
     * @return the value of md_log_operation.pk_operation_id
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public String getPkOperationId() {
        return pkOperationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_log_operation.pk_operation_id
     *
     * @param pkOperationId the value for md_log_operation.pk_operation_id
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public void setPkOperationId(String pkOperationId) {
        this.pkOperationId = pkOperationId == null ? null : pkOperationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_log_operation.beforeData
     *
     * @return the value of md_log_operation.beforeData
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public String getBeforedata() {
        return beforedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_log_operation.beforeData
     *
     * @param beforedata the value for md_log_operation.beforeData
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public void setBeforedata(String beforedata) {
        this.beforedata = beforedata == null ? null : beforedata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_log_operation.afterData
     *
     * @return the value of md_log_operation.afterData
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public String getAfterdata() {
        return afterdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_log_operation.afterData
     *
     * @param afterdata the value for md_log_operation.afterData
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public void setAfterdata(String afterdata) {
        this.afterdata = afterdata == null ? null : afterdata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_log_operation.create_time
     *
     * @return the value of md_log_operation.create_time
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_log_operation.create_time
     *
     * @param createTime the value for md_log_operation.create_time
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_log_operation.memo
     *
     * @return the value of md_log_operation.memo
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_log_operation.memo
     *
     * @param memo the value for md_log_operation.memo
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_log_operation.log_num
     *
     * @return the value of md_log_operation.log_num
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public String getLogNum() {
        return logNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_log_operation.log_num
     *
     * @param logNum the value for md_log_operation.log_num
     *
     * @mbg.generated Sun Nov 25 11:46:30 CST 2018
     */
    public void setLogNum(String logNum) {
        this.logNum = logNum == null ? null : logNum.trim();
    }
}