package com.media.common.model.stuff;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActivityRuleExpExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    public ActivityRuleExpExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkRuleExpressionIdIsNull() {
            addCriterion("pk_rule_expression_id is null");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdIsNotNull() {
            addCriterion("pk_rule_expression_id is not null");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdEqualTo(String value) {
            addCriterion("pk_rule_expression_id =", value, "pkRuleExpressionId");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdNotEqualTo(String value) {
            addCriterion("pk_rule_expression_id <>", value, "pkRuleExpressionId");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdGreaterThan(String value) {
            addCriterion("pk_rule_expression_id >", value, "pkRuleExpressionId");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdGreaterThanOrEqualTo(String value) {
            addCriterion("pk_rule_expression_id >=", value, "pkRuleExpressionId");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdLessThan(String value) {
            addCriterion("pk_rule_expression_id <", value, "pkRuleExpressionId");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdLessThanOrEqualTo(String value) {
            addCriterion("pk_rule_expression_id <=", value, "pkRuleExpressionId");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdLike(String value) {
            addCriterion("pk_rule_expression_id like", value, "pkRuleExpressionId");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdNotLike(String value) {
            addCriterion("pk_rule_expression_id not like", value, "pkRuleExpressionId");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdIn(List<String> values) {
            addCriterion("pk_rule_expression_id in", values, "pkRuleExpressionId");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdNotIn(List<String> values) {
            addCriterion("pk_rule_expression_id not in", values, "pkRuleExpressionId");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdBetween(String value1, String value2) {
            addCriterion("pk_rule_expression_id between", value1, value2, "pkRuleExpressionId");
            return (Criteria) this;
        }

        public Criteria andPkRuleExpressionIdNotBetween(String value1, String value2) {
            addCriterion("pk_rule_expression_id not between", value1, value2, "pkRuleExpressionId");
            return (Criteria) this;
        }

        public Criteria andSelectGoodsTypeIsNull() {
            addCriterion("select_goods_type is null");
            return (Criteria) this;
        }

        public Criteria andSelectGoodsTypeIsNotNull() {
            addCriterion("select_goods_type is not null");
            return (Criteria) this;
        }

        public Criteria andSelectGoodsTypeEqualTo(Integer value) {
            addCriterion("select_goods_type =", value, "selectGoodsType");
            return (Criteria) this;
        }

        public Criteria andSelectGoodsTypeNotEqualTo(Integer value) {
            addCriterion("select_goods_type <>", value, "selectGoodsType");
            return (Criteria) this;
        }

        public Criteria andSelectGoodsTypeGreaterThan(Integer value) {
            addCriterion("select_goods_type >", value, "selectGoodsType");
            return (Criteria) this;
        }

        public Criteria andSelectGoodsTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("select_goods_type >=", value, "selectGoodsType");
            return (Criteria) this;
        }

        public Criteria andSelectGoodsTypeLessThan(Integer value) {
            addCriterion("select_goods_type <", value, "selectGoodsType");
            return (Criteria) this;
        }

        public Criteria andSelectGoodsTypeLessThanOrEqualTo(Integer value) {
            addCriterion("select_goods_type <=", value, "selectGoodsType");
            return (Criteria) this;
        }

        public Criteria andSelectGoodsTypeIn(List<Integer> values) {
            addCriterion("select_goods_type in", values, "selectGoodsType");
            return (Criteria) this;
        }

        public Criteria andSelectGoodsTypeNotIn(List<Integer> values) {
            addCriterion("select_goods_type not in", values, "selectGoodsType");
            return (Criteria) this;
        }

        public Criteria andSelectGoodsTypeBetween(Integer value1, Integer value2) {
            addCriterion("select_goods_type between", value1, value2, "selectGoodsType");
            return (Criteria) this;
        }

        public Criteria andSelectGoodsTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("select_goods_type not between", value1, value2, "selectGoodsType");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNull() {
            addCriterion("total_price is null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNotNull() {
            addCriterion("total_price is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceEqualTo(Double value) {
            addCriterion("total_price =", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotEqualTo(Double value) {
            addCriterion("total_price <>", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThan(Double value) {
            addCriterion("total_price >", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("total_price >=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThan(Double value) {
            addCriterion("total_price <", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThanOrEqualTo(Double value) {
            addCriterion("total_price <=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIn(List<Double> values) {
            addCriterion("total_price in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotIn(List<Double> values) {
            addCriterion("total_price not in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceBetween(Double value1, Double value2) {
            addCriterion("total_price between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotBetween(Double value1, Double value2) {
            addCriterion("total_price not between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalDiscountIsNull() {
            addCriterion("total_discount is null");
            return (Criteria) this;
        }

        public Criteria andTotalDiscountIsNotNull() {
            addCriterion("total_discount is not null");
            return (Criteria) this;
        }

        public Criteria andTotalDiscountEqualTo(Double value) {
            addCriterion("total_discount =", value, "totalDiscount");
            return (Criteria) this;
        }

        public Criteria andTotalDiscountNotEqualTo(Double value) {
            addCriterion("total_discount <>", value, "totalDiscount");
            return (Criteria) this;
        }

        public Criteria andTotalDiscountGreaterThan(Double value) {
            addCriterion("total_discount >", value, "totalDiscount");
            return (Criteria) this;
        }

        public Criteria andTotalDiscountGreaterThanOrEqualTo(Double value) {
            addCriterion("total_discount >=", value, "totalDiscount");
            return (Criteria) this;
        }

        public Criteria andTotalDiscountLessThan(Double value) {
            addCriterion("total_discount <", value, "totalDiscount");
            return (Criteria) this;
        }

        public Criteria andTotalDiscountLessThanOrEqualTo(Double value) {
            addCriterion("total_discount <=", value, "totalDiscount");
            return (Criteria) this;
        }

        public Criteria andTotalDiscountIn(List<Double> values) {
            addCriterion("total_discount in", values, "totalDiscount");
            return (Criteria) this;
        }

        public Criteria andTotalDiscountNotIn(List<Double> values) {
            addCriterion("total_discount not in", values, "totalDiscount");
            return (Criteria) this;
        }

        public Criteria andTotalDiscountBetween(Double value1, Double value2) {
            addCriterion("total_discount between", value1, value2, "totalDiscount");
            return (Criteria) this;
        }

        public Criteria andTotalDiscountNotBetween(Double value1, Double value2) {
            addCriterion("total_discount not between", value1, value2, "totalDiscount");
            return (Criteria) this;
        }

        public Criteria andTotalNumberIsNull() {
            addCriterion("total_number is null");
            return (Criteria) this;
        }

        public Criteria andTotalNumberIsNotNull() {
            addCriterion("total_number is not null");
            return (Criteria) this;
        }

        public Criteria andTotalNumberEqualTo(Integer value) {
            addCriterion("total_number =", value, "totalNumber");
            return (Criteria) this;
        }

        public Criteria andTotalNumberNotEqualTo(Integer value) {
            addCriterion("total_number <>", value, "totalNumber");
            return (Criteria) this;
        }

        public Criteria andTotalNumberGreaterThan(Integer value) {
            addCriterion("total_number >", value, "totalNumber");
            return (Criteria) this;
        }

        public Criteria andTotalNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_number >=", value, "totalNumber");
            return (Criteria) this;
        }

        public Criteria andTotalNumberLessThan(Integer value) {
            addCriterion("total_number <", value, "totalNumber");
            return (Criteria) this;
        }

        public Criteria andTotalNumberLessThanOrEqualTo(Integer value) {
            addCriterion("total_number <=", value, "totalNumber");
            return (Criteria) this;
        }

        public Criteria andTotalNumberIn(List<Integer> values) {
            addCriterion("total_number in", values, "totalNumber");
            return (Criteria) this;
        }

        public Criteria andTotalNumberNotIn(List<Integer> values) {
            addCriterion("total_number not in", values, "totalNumber");
            return (Criteria) this;
        }

        public Criteria andTotalNumberBetween(Integer value1, Integer value2) {
            addCriterion("total_number between", value1, value2, "totalNumber");
            return (Criteria) this;
        }

        public Criteria andTotalNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("total_number not between", value1, value2, "totalNumber");
            return (Criteria) this;
        }

        public Criteria andTotalPresentIsNull() {
            addCriterion("total_present is null");
            return (Criteria) this;
        }

        public Criteria andTotalPresentIsNotNull() {
            addCriterion("total_present is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPresentEqualTo(Integer value) {
            addCriterion("total_present =", value, "totalPresent");
            return (Criteria) this;
        }

        public Criteria andTotalPresentNotEqualTo(Integer value) {
            addCriterion("total_present <>", value, "totalPresent");
            return (Criteria) this;
        }

        public Criteria andTotalPresentGreaterThan(Integer value) {
            addCriterion("total_present >", value, "totalPresent");
            return (Criteria) this;
        }

        public Criteria andTotalPresentGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_present >=", value, "totalPresent");
            return (Criteria) this;
        }

        public Criteria andTotalPresentLessThan(Integer value) {
            addCriterion("total_present <", value, "totalPresent");
            return (Criteria) this;
        }

        public Criteria andTotalPresentLessThanOrEqualTo(Integer value) {
            addCriterion("total_present <=", value, "totalPresent");
            return (Criteria) this;
        }

        public Criteria andTotalPresentIn(List<Integer> values) {
            addCriterion("total_present in", values, "totalPresent");
            return (Criteria) this;
        }

        public Criteria andTotalPresentNotIn(List<Integer> values) {
            addCriterion("total_present not in", values, "totalPresent");
            return (Criteria) this;
        }

        public Criteria andTotalPresentBetween(Integer value1, Integer value2) {
            addCriterion("total_present between", value1, value2, "totalPresent");
            return (Criteria) this;
        }

        public Criteria andTotalPresentNotBetween(Integer value1, Integer value2) {
            addCriterion("total_present not between", value1, value2, "totalPresent");
            return (Criteria) this;
        }

        public Criteria andPriceDiscountIsNull() {
            addCriterion("price_discount is null");
            return (Criteria) this;
        }

        public Criteria andPriceDiscountIsNotNull() {
            addCriterion("price_discount is not null");
            return (Criteria) this;
        }

        public Criteria andPriceDiscountEqualTo(Integer value) {
            addCriterion("price_discount =", value, "priceDiscount");
            return (Criteria) this;
        }

        public Criteria andPriceDiscountNotEqualTo(Integer value) {
            addCriterion("price_discount <>", value, "priceDiscount");
            return (Criteria) this;
        }

        public Criteria andPriceDiscountGreaterThan(Integer value) {
            addCriterion("price_discount >", value, "priceDiscount");
            return (Criteria) this;
        }

        public Criteria andPriceDiscountGreaterThanOrEqualTo(Integer value) {
            addCriterion("price_discount >=", value, "priceDiscount");
            return (Criteria) this;
        }

        public Criteria andPriceDiscountLessThan(Integer value) {
            addCriterion("price_discount <", value, "priceDiscount");
            return (Criteria) this;
        }

        public Criteria andPriceDiscountLessThanOrEqualTo(Integer value) {
            addCriterion("price_discount <=", value, "priceDiscount");
            return (Criteria) this;
        }

        public Criteria andPriceDiscountIn(List<Integer> values) {
            addCriterion("price_discount in", values, "priceDiscount");
            return (Criteria) this;
        }

        public Criteria andPriceDiscountNotIn(List<Integer> values) {
            addCriterion("price_discount not in", values, "priceDiscount");
            return (Criteria) this;
        }

        public Criteria andPriceDiscountBetween(Integer value1, Integer value2) {
            addCriterion("price_discount between", value1, value2, "priceDiscount");
            return (Criteria) this;
        }

        public Criteria andPriceDiscountNotBetween(Integer value1, Integer value2) {
            addCriterion("price_discount not between", value1, value2, "priceDiscount");
            return (Criteria) this;
        }

        public Criteria andStuffLevelIsNull() {
            addCriterion("stuff_level is null");
            return (Criteria) this;
        }

        public Criteria andStuffLevelIsNotNull() {
            addCriterion("stuff_level is not null");
            return (Criteria) this;
        }

        public Criteria andStuffLevelEqualTo(Integer value) {
            addCriterion("stuff_level =", value, "stuffLevel");
            return (Criteria) this;
        }

        public Criteria andStuffLevelNotEqualTo(Integer value) {
            addCriterion("stuff_level <>", value, "stuffLevel");
            return (Criteria) this;
        }

        public Criteria andStuffLevelGreaterThan(Integer value) {
            addCriterion("stuff_level >", value, "stuffLevel");
            return (Criteria) this;
        }

        public Criteria andStuffLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("stuff_level >=", value, "stuffLevel");
            return (Criteria) this;
        }

        public Criteria andStuffLevelLessThan(Integer value) {
            addCriterion("stuff_level <", value, "stuffLevel");
            return (Criteria) this;
        }

        public Criteria andStuffLevelLessThanOrEqualTo(Integer value) {
            addCriterion("stuff_level <=", value, "stuffLevel");
            return (Criteria) this;
        }

        public Criteria andStuffLevelIn(List<Integer> values) {
            addCriterion("stuff_level in", values, "stuffLevel");
            return (Criteria) this;
        }

        public Criteria andStuffLevelNotIn(List<Integer> values) {
            addCriterion("stuff_level not in", values, "stuffLevel");
            return (Criteria) this;
        }

        public Criteria andStuffLevelBetween(Integer value1, Integer value2) {
            addCriterion("stuff_level between", value1, value2, "stuffLevel");
            return (Criteria) this;
        }

        public Criteria andStuffLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("stuff_level not between", value1, value2, "stuffLevel");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated do_not_delete_during_merge Wed Oct 24 13:38:47 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table md_stuff_rule_expression
     *
     * @mbg.generated Wed Oct 24 13:38:47 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}