package com.media.common.model.agency;

import com.media.common.base.BaseModel;
import java.util.Date;

public class Agency extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_agency.agency_id
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    private String agencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_agency.agency_code
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    private String agencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_agency.agency_name
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    private String agencyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_agency.parent_id
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_agency.create_time
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_agency.create_user_id
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_agency.last_modify_time
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_agency.last_modify_user_id
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    private String lastModifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_agency.memo
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_agency.tel_phone
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    private String telPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_agency.status
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_agency.agency_id
     *
     * @return the value of md_agency.agency_id
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public String getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_agency.agency_id
     *
     * @param agencyId the value for md_agency.agency_id
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public void setAgencyId(String agencyId) {
        this.agencyId = agencyId == null ? null : agencyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_agency.agency_code
     *
     * @return the value of md_agency.agency_code
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public String getAgencyCode() {
        return agencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_agency.agency_code
     *
     * @param agencyCode the value for md_agency.agency_code
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public void setAgencyCode(String agencyCode) {
        this.agencyCode = agencyCode == null ? null : agencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_agency.agency_name
     *
     * @return the value of md_agency.agency_name
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public String getAgencyName() {
        return agencyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_agency.agency_name
     *
     * @param agencyName the value for md_agency.agency_name
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName == null ? null : agencyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_agency.parent_id
     *
     * @return the value of md_agency.parent_id
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_agency.parent_id
     *
     * @param parentId the value for md_agency.parent_id
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_agency.create_time
     *
     * @return the value of md_agency.create_time
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_agency.create_time
     *
     * @param createTime the value for md_agency.create_time
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_agency.create_user_id
     *
     * @return the value of md_agency.create_user_id
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_agency.create_user_id
     *
     * @param createUserId the value for md_agency.create_user_id
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_agency.last_modify_time
     *
     * @return the value of md_agency.last_modify_time
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_agency.last_modify_time
     *
     * @param lastModifyTime the value for md_agency.last_modify_time
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_agency.last_modify_user_id
     *
     * @return the value of md_agency.last_modify_user_id
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public String getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_agency.last_modify_user_id
     *
     * @param lastModifyUserId the value for md_agency.last_modify_user_id
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public void setLastModifyUserId(String lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId == null ? null : lastModifyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_agency.memo
     *
     * @return the value of md_agency.memo
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_agency.memo
     *
     * @param memo the value for md_agency.memo
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_agency.tel_phone
     *
     * @return the value of md_agency.tel_phone
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public String getTelPhone() {
        return telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_agency.tel_phone
     *
     * @param telPhone the value for md_agency.tel_phone
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public void setTelPhone(String telPhone) {
        this.telPhone = telPhone == null ? null : telPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_agency.status
     *
     * @return the value of md_agency.status
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_agency.status
     *
     * @param status the value for md_agency.status
     *
     * @mbg.generated Mon Oct 29 14:38:02 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}