package com.media.common.model.user;

import com.media.common.base.BaseModel;
import java.util.Date;

public class UserRole extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user_role.user_role_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    private String userRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user_role.user_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user_role.role_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user_role.status
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user_role.create_time
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user_role.create_user_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user_role.last_modify_time
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user_role.last_modify_user_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    private String lastModifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user_role.agency_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    private String agencyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user_role.user_role_id
     *
     * @return the value of md_user_role.user_role_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public String getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user_role.user_role_id
     *
     * @param userRoleId the value for md_user_role.user_role_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public void setUserRoleId(String userRoleId) {
        this.userRoleId = userRoleId == null ? null : userRoleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user_role.user_id
     *
     * @return the value of md_user_role.user_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user_role.user_id
     *
     * @param userId the value for md_user_role.user_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user_role.role_id
     *
     * @return the value of md_user_role.role_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user_role.role_id
     *
     * @param roleId the value for md_user_role.role_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user_role.status
     *
     * @return the value of md_user_role.status
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user_role.status
     *
     * @param status the value for md_user_role.status
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user_role.create_time
     *
     * @return the value of md_user_role.create_time
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user_role.create_time
     *
     * @param createTime the value for md_user_role.create_time
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user_role.create_user_id
     *
     * @return the value of md_user_role.create_user_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user_role.create_user_id
     *
     * @param createUserId the value for md_user_role.create_user_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user_role.last_modify_time
     *
     * @return the value of md_user_role.last_modify_time
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user_role.last_modify_time
     *
     * @param lastModifyTime the value for md_user_role.last_modify_time
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user_role.last_modify_user_id
     *
     * @return the value of md_user_role.last_modify_user_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public String getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user_role.last_modify_user_id
     *
     * @param lastModifyUserId the value for md_user_role.last_modify_user_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public void setLastModifyUserId(String lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId == null ? null : lastModifyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user_role.agency_id
     *
     * @return the value of md_user_role.agency_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public String getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user_role.agency_id
     *
     * @param agencyId the value for md_user_role.agency_id
     *
     * @mbg.generated Tue Nov 27 13:48:59 CST 2018
     */
    public void setAgencyId(String agencyId) {
        this.agencyId = agencyId == null ? null : agencyId.trim();
    }

	@Override
	public String toString() {
		return "UserRole [userRoleId=" + userRoleId + ", userId=" + userId + ", roleId=" + roleId + ", status=" + status
				+ ", createTime=" + createTime + ", createUserId=" + createUserId + ", lastModifyTime=" + lastModifyTime
				+ ", lastModifyUserId=" + lastModifyUserId + ", agencyId=" + agencyId + "]";
	}
    
}